#163383179 Add funtionality fro
andela/ah-backend-summer pull request #20
Opened 2019-02-04 12:11 UTC by oma0256

…d update a user's profile

 - ensure a user can view their profile
 - ensure a user can view another user's profile
 - ensure user can edit their profile
 - ensure user cannot edit another user's profile

[Starts #163383179]

2019-02-04 13:36 UTC, fahdjamy approved these changes

2019-02-04 13:59 UTC, missvicki reviewed
Oma nice work. Do we really have to use regular expressions in the url. Can't we avoid them?

2019-02-04 14:05 UTC, FahdJamy commented
> Oma nice work. Do we really have to use regular expressions in the URL? Can't we avoid them?

Yeah, I think like we had agreed @oma0256. you should stick to using regular expressions in the urls.

2019-02-04 14:11 UTC, oma0256 commented
@missvicki had to use them in this case since there's no way I can match username without using regular expressions.

2019-02-04 15:00 UTC, codjoero commented
@oma0256, Great work, but we are going to have to try and get rid of re_path see what happens.

2019-02-04 15:06 UTC, oma0256 commented
@codjoero @missvicki thanks for the feedback got rid of the regular expressions and used path

2019-02-04 15:06 UTC, codjoero approved these changes
I knew you could  do it, 
LGTM

2019-02-04 15:08 UTC, pbkabali commented
Works fine. Good work @oma0256. I need to find you and you explain to me why we absolutely need the re_path in the url.

2019-02-04 15:09 UTC, pbkabali approved these changes

2019-02-04 15:11 UTC, oma0256 commented
@pbkabali It was a mistake on my side fixed it now using path instead of re_path

2019-02-05 11:23 UTC, karuhanga requested changes
Good work on implementing this feature @oma0256.
A few thoughts;
- I think the names of the test methods could improve, for example it would be clearer to write `test_unauthenticated_user_cannot_update_a_profile` than `test_update_profile_when_unauthorized`, as the former clearly states what you need to achieve, or `test_user_cannot_update_another_users_profile` than `test_update_profile_for_different_user`.
- It is not clear from the updates to the `settings` how the image upload will work in production, especially given heroku's model does not support this. Could we perhaps we could look into uploading the images to another service like `aws` in production?

2019-02-05 11:23 UTC, karuhanga commented on authors/apps/profiles/tests/test_update_profile.py
> +    def test_update_profile_successfully(self):
I don't think this test achieves what you are trying to, that is you only check for whether or not what is returned is `None`, and not necessarily if it is the same as the update data.

2019-02-05 13:10 UTC, malep2007 requested changes

2019-02-05 13:10 UTC, malep2007 commented on authors/apps/authentication/models.py
> +def profile_post_save_reciever(sender, instance, created, *args, **kwargs):
I think you should take advantage of python's kwargs to reduce the number of parameters that you pass to this method.
For this, you could easily re-write it as follows
```python
def profile_post_save_receiver(*args, **kwargs):
    sender = kwargs.get('sender')
    instance = kwargs.get('instance')
    created = kwargs.get('created')
    user = instance.user
    user.username = instance.username
    user.save(update_fields=['username])
```

2019-02-05 13:10 UTC, malep2007 commented on authors/apps/authentication/models.py
> +def profile_post_save_reciever(sender, instance, created, *args, **kwargs):
You can do the same for areas where you have many parameters in a method call. PEP8 requires no more than 4 parameters in a method call

2019-02-05 13:10 UTC, malep2007 commented on authors/apps/profiles/tests/test_update_profile.py
> +    def test_update_profile_successfully(self):
I agree you should check to explicitly see of the updated `bio` information is what you expect. Remember tests should be explicit.

2019-02-06 07:55 UTC, malep2007 approved these changes

2019-02-06 07:55 UTC, merged