feat(favorite-unfavroite-article): implement favorite and unfavorite …
andela/ah-backend-summer pull request #32
Opened 2019-02-11 16:59 UTC by oma0256

**What does this PR do?**
 - Allow an authenticated user to favourite and unfavourite an article.
 - Prevent an unauthenticated user from favouriting and unfavouriting an article.

**How should this be manually tested?**
 - Download and install postman onto you're local machine
 - Open postman
- Register a user using the route 
`https://ah-backend-summer-stagin-pr-32.herokuapp.com/api/v1/users/`
- Login the user you just registered
`https://ah-backend-summer-stagin-pr-32.herokuapp.com/api/v1/users/login/`
- Get the token that was returned
- Insert a header in postman with a key of `Authorization`  and value `Bearer <token>`
- Then visit the route `https://ah-backend-summer-stagin-pr-32.herokuapp.com/api/v1/articles` to create an article using `POST`.
- Then visit the route `https://ah-backend-summer-stagin-pr-32.herokuapp.com/http://127.0.0.1:8000/api/v1/articles/<slug>/favorite` to favourite or unfavourite an article `POST`.
- Then visit the route `https://ah-backend-summer-stagin-pr-32.herokuapp.com/http://127.0.0.1:8000/api/v1/articles/<slug>/unfavorite` to unfavourite an article `DELETE`.

**What are the relevant pivotal tracker stories?**
[#163383187](https://www.pivotaltracker.com/n/projects/2240000/stories/163383187)

2019-02-11 16:59 UTC, pep8speaks commented
Hello @oma0256! Thanks for submitting the PR.





 - In the file [`authors/apps/articles/tests/test_article_api_endpoints.py`](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py), following are the PEP8 issues :

> [Line 100:36](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L100): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 101:36](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L101): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 114:44](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L114): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 115:36](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L115): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 116:36](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L116): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 130:44](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L130): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 133:36](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L133): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 134:36](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L134): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 193:1](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L193): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 196:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L196): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 208:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L208): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 213:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L213): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 214:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L214): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 219:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L219): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 221:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L221): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 226:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L226): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 227:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L227): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 232:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L232): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 234:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L234): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 239:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L239): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 245:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L245): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 247:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L247): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 253:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L253): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 258:80](https://github.com/andela/ah-backend-summer/blob/be815bd3d4b4f6572e36fed53eabd6efd45d9410/authors/apps/articles/tests/test_article_api_endpoints.py#L258): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)

2019-02-11 18:59 UTC, missvicki requested changes
resolve pep8 issues

2019-02-12 07:11 UTC, pbkabali commented on authors/apps/articles/views.py
> +        article = get_single_article_using_slug(slug)
bhhh

2019-02-12 07:21 UTC, karuhanga approved these changes
LGTM.

2019-02-12 07:24 UTC, pbkabali commented
Great work @oma0256. I would have thought thou that it is easier to just create a different HTTP method in the same class for the un-favoriting view. Otherwise it all LGTM

2019-02-12 07:24 UTC, pbkabali approved these changes

2019-02-12 07:27 UTC, fahdjamy approved these changes
Great Work @oma0256.

2019-02-12 07:48 UTC, codjoero approved these changes
LGTM

2019-02-12 07:49 UTC, missvicki approved these changes

2019-02-13 06:48 UTC, merged