#163383194 Implement Users should be able to share articles
andela/ah-backend-summer pull request #44
Opened 2019-02-19 15:17 UTC by missvicki

#### What does this PR do?

 Implement Users should be able to share articles across different channels

#### Description of Task to be completed?

- write tests to get sharable links for Facebook, Twitter, Google and email
- write method creates links that will be used to post an article to
    Facebook and Google Plus, or share an article as a tweet on Twitter
    and also share the article through email to another email user

#### How should this be manually tested?

* Fetch and checkout this branch `ft-bookmark-article-163383195`
* Create a virtual environment using `python3 -m virtualenv venv`  and activate it using `source venv\bin\activate`
* Install requirements using `pip install -r requirements.txt`
* Start the app `python manage.py runserver`

#### What are the relevant pivotal tracker stories?

[#163383194](https://www.pivotaltracker.com/story/show/163383194)

#### Screenshots 

<img width="1099" alt="screenshot 2019-02-19 at 18 17 19" src="https://user-images.githubusercontent.com/31304859/53025776-9c04ff00-3472-11e9-888e-82d445241739.png">

2019-02-19 15:22 UTC, pep8speaks commented
Hello @missvicki! Thanks for submitting the PR.





 - In the file [`authors/apps/articles/utils/utils.py`](https://github.com/andela/ah-backend-summer/blob/68c5782c85f5941b2de4336bb4c1c9879cd147e1/authors/apps/articles/utils/utils.py), following are the PEP8 issues :

> [Line 55:72](https://github.com/andela/ah-backend-summer/blob/68c5782c85f5941b2de4336bb4c1c9879cd147e1/authors/apps/articles/utils/utils.py#L55): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2019-02-20 08:45 UTC, FahdJamy commented
Thanks for the simple and good implementation of the task.
Do you mind just dealing with the pep8 white space

2019-02-20 09:04 UTC, missvicki commented
> Thanks for the simple and good implementation of the task.
> Do you mind just dealing with the pep8 white space

working on this.

2019-02-20 09:35 UTC, codjoero requested changes

2019-02-20 09:35 UTC, codjoero commented on authors/apps/articles/utils/utils.py
> +with you. Click this link:{url}"""
Good work @missvicki , Am wondering why you had to use the doc-string quotes in the f-string

2019-02-20 09:36 UTC, missvicki commented on authors/apps/articles/utils/utils.py
> +with you. Click this link:{url}"""
I wanted to be able to use the qoutation e.g. 'this is my subject' within the body message

2019-02-20 09:37 UTC, codjoero approved these changes
LGTM

2019-02-20 15:49 UTC, karuhanga approved these changes
LGTM

2019-02-20 17:09 UTC, oma0256 approved these changes
Good work @missvicki

2019-02-21 01:33 UTC, pbkabali approved these changes

2019-02-21 06:41 UTC, malep2007 reviewed
You could do the same thing here, with this PR to improve the description.

2019-02-21 11:37 UTC, malep2007 commented
@missvicki some merge conflicts here.

2019-02-21 11:43 UTC, missvicki commented
> @missvicki some merge conflicts here.

Resolved

2019-02-21 11:44 UTC, fahdjamy approved these changes

2019-02-21 12:14 UTC, merged